name = "GNN_FQNS"
uuid = "8012000a-36b7-419d-a57d-29bda53e9aa4"
version = "1.0.0-DEV"
authors = ["Javad Vahedi"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
BSON = "0.3.9"
CUDA = "5.9.4"
CairoMakie = "0.15.6"
Distributed = "1.11.0"
Flux = "0.16.5"
LinearAlgebra = "1.12.0"
Printf = "1.11.0"
Random = "1.11.0"
Serialization = "1.11.0"
Statistics = "1.11.1"
Zygote = "0.7.10"
cuDNN = "1.4.6"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
